language: node_js
node_js:
  - 14.4.0
  - 8
  - 10
notifications:
  email:
    on_success: change
    on_failure: change
sudo: false
after_success:
  - npm install -g codecov
  - codecov -f coverage/full/lcov.info
